config/routes.rb
Admin::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :followers, :controllers => { :omniauth_callbacks => "followers/omniauth_callbacks" }

  resources :posts do #, except: :show
   match '(/:yy(/:mm))' => "posts#search", on: :collection, as: :search, via: :get
   resources :post_comments, path: 'comments'
  end
  get 'posts/:yy/:mm/:id' => 'posts#view', as: :post_show
  
  resources :profiles, only: :show, path: 'profile'
  resources :followers, only: :index, path: 'follower'
  
  

  root to: 'posts#index'

  
end

app/views/shared/_footer.html.haml
Powered by 
%b 
  %u kishore@rubyeffect.com

app/views/shared/_sidebar.html.haml
.about.clearfix
  %h4 ABOUT ME
  %p
    =# image_tag(@admin.profile.image.url(:thumb)) if @admin.profile
    = link_to image_tag("Image0001.JPG", width: 80, height: 80), "#" if @admin.profile
  %p
    %b= link_to_admin_profile(@admin)
  = link_to "View my complete profile", profile_path(@admin.profile) if @admin.profile
%br/  
.blogs-list.clearfix
  %h4 BLOG ARCHIVE
  = link_to_all_posts
%br/
.followers.clearfix
  .user-links
    - if current_follower
      .btn-group
        %button.btn.btn-inverse
          = current_follower.email
        %button.btn.btn-inverse.dropdown-toggle{"data-toggle" => "dropdown"}
          %span.caret
        %ul.dropdown-menu
          - if @admin.followers.include?(current_follower)
            %li
              = link_to "<b>UnFollow</b> this Blog".html_safe, followers_path(type: 'unfollow')
          - else
            %li
              = link_to "<b>Follow</b> this Blog".html_safe, followers_path(type: 'follow')
          %li.divider
          %li= link_to "Sign Out", destroy_follower_session_path, method: :delete   
    - else
      .btn-group
        %button.btn.btn-inverse
          Not a member, yet?
        %button.btn.btn-inverse.dropdown-toggle{"data-toggle" => "dropdown"}
          %span.caret
        %ul.dropdown-menu
          %li= link_to "Sign up with your email", new_follower_registration_path, method: :get
          %li.divider
          %li= link_to "Sign up/Sign in with Facebook", follower_omniauth_authorize_path(:facebook), class: "popup", "data-width" => 600, "data-height" => 400
          %li= link_to "Sign up/Sign in with Google", follower_omniauth_authorize_path(:google_oauth2), class: "popup", "data-width" => 600, "data-height" => 400
  %hr      
  %h4 Followers
  = followers
  .follow-pics
    - @admin.followers.each do |follow|
      %p= image_tag("NoPicture.jpg", title: follow.email)
  %br
  - if !current_follower
    .member
      %span Already a member?
      %b= link_to "Sign In", new_follower_session_path, method: :get

%br
.fb-like-box{"data-colorscheme" => "light", "data-header" => "true", "data-height" => "210", "data-href" => "https://www.facebook.com/pages/Krishtech/133762500141155", "data-show-border" => "true", "data-show-faces" => "true", "data-stream" => "false", "data-width" => "280", style: "background:#efefef;"}
      
    
:javascript
  $(document).ready(function() {
     $(".arrow").click(function() {
       var id = $(this).attr('id');
       $(this).toggleClass('toggle-arrow');
       $("."+id+"_posts").toggle();
    });
  });