config/routes.rb
Admin::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :followers, :controllers => { :omniauth_callbacks => "followers/omniauth_callbacks" }

  resources :posts do #, except: :show
   match '(/:yy(/:mm))' => "posts#search", on: :collection, as: :search, via: :get
   resources :post_comments, path: 'comments'
  end
  get 'posts/:yy/:mm/:id' => 'posts#view', as: :post_show
  
  resources :profiles, only: :show, path: 'profile'
  resources :followers, only: :index, path: 'follower'
  
  

  root to: 'posts#index'

  
end

app/models/post.rb
class Post < ActiveRecord::Base
 # def to_param
 #   title.parameterize
 # end
 has_many :comments, class_name: 'PostComment', dependent: :destroy
 belongs_to :user, class_name: "AdminUser", foreign_key: :admin_user_id
 validates :title, presence: true, uniqueness: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin_user!, except: %w(index show destroy view search)
  before_filter :load_post, only: %w(destroy edit update show view)

  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @post.update_attributes(post_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def view
   # @comment = @post.comments.build
  end
  
  def destroy
   @post.destroy
   redirect_to :back
  end
  
  def search
    redirect_to root_path if params[:yy].blank? && params[:mm].blank?
    query = []
    query << "(extract(year from created_at) = '#{params[:yy]}')" if params[:yy]
    query << "(extract(month from created_at) = '#{params[:mm]}')" if params[:mm]
    #query << "YEAR(created_at) = '#{params[:yy]}'" if params[:yy]
    #query << "MONTH(created_at) = '#{params[:mm]}'" if params[:mm]
    Rails.logger.debug "\n.......#{query.join(" AND ")}\n"
    @posts = Post.where(query.join(" AND "))
  end
  
  private
  def load_post
    #@post = Post.find(params[:id])
    @post = Post.find_by(title: params[:id].gsub("-", " "))
  end
  
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def link_to_all_posts
    posts = Post.all 
    html = ""
    lists1 = posts.group_by { |p| p.created_at.strftime("%Y") }
    lists1.each do |year, list|
      html << "<h5><span><i class='arrow' id='#{year}'></i></span> "+ link_to_filter(year, list.size, "yy") +"</h5>"
      html << "<ul class='#{year}_posts main'>"
      lists = list.group_by { |p| p.created_at.strftime("%B") }
      lists.each do |date, list|
        html << "<li class='main'>"
        mm = list.first.created_at.strftime("%m")
        html << "<h5><span><i class='arrow' id='#{year}_#{mm}'></i></span>"+ link_to_filter(date, list.size, "mm_#{year}_#{mm}") +"</h5>"
        html << "<ul class='#{year}_#{mm}_posts'>"
        list.each do |post|
          html << "<li>" + post_url(post) + "</li>"
        end
        html << "</li></ul>"
      end
      html << "</ul>"
    end
    html.html_safe
  end
  
  def link_to_filter(date, count, type)
    txt = date.to_s + '('+ count.to_s + ')'
    if type == "yy"
      link_to txt, search_posts_path(date, nil)
    else
      yy, mm = type.scan(/\d+/)
      link_to txt, search_posts_path(yy, mm)
    end
  end

  def post_url(post)
    link_to post.title, post_show_path(yy: post.created_at.strftime("%Y"), mm: post.created_at.strftime("%m"), id: post.title.gsub(" ", "-"))
  end
  
  def format_content(data)
    #simple_format(data.gsub("     ", "&nbsp; &nbsp;")) #OR
    (h(data).gsub(/\n/, '<br/>').gsub("  ", "&nbsp; &nbsp;")).html_safe 
  end
end

app/views/posts/_comment_form.html.haml
= form_for [@post, @comment] do |f|
  %p= f.hidden_field :follower_id, value: current_follower.id if current_follower
  %p= f.text_area :text
  %p= f.select :type, ["Anonymous", "As a member"]
  %p= f.submit "Save"

app/views/posts/_form.html.haml
= form_for @post do |f|
  %p= f.text_field :title
  %p= f.text_area :content
  %p= f.submit "Save"

app/views/posts/_list.html.haml
- unless @posts.blank?
  %ul
    - posts = @posts.group_by{ |item| item.created_at.to_date }
    - posts.each do |date, list|
      .day-wise
        %h2= date.strftime("%A, %d %B %Y")
        - list.each do |post|
          %li
            .post-outer
              %h5
                = link_to post.title.titleize, post_show_path(yy: post.created_at.strftime("%Y"), mm: post.created_at.strftime("%m"), id: post.title.gsub(" ", "-"))
              %p
                = post.content.html_safe
              %br
              %p
                Posted by
                = link_to post.user.full_name, "#"
                at
                = post.created_at.strftime("%H:%M")
                &nbsp;&nbsp;&nbsp;
                %span.fb-like{"data-action" => "like", "data-href" => post_show_url(yy: post.created_at.strftime("%Y"), mm: post.created_at.strftime("%m"), id: post.title.gsub(" ", "-")), "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true", style: "float:right;"}
                &nbsp;&nbsp;&nbsp;
                = render 'post', post: post
              - if current_admin_user
                .links
                  = link_to "Edit", edit_admin_post_path(post)
                  |
                  = link_to "Delete", post_path(post.title.parameterize), data: { confirm: 'Are you sure?' }, method: :delete
- else
  No posts found
  

app/views/posts/_post.html.erb
<%= link_to "", post_show_path(yy: post.created_at.strftime("%Y"), mm: post.created_at.strftime("%m"), id: post.title.gsub(" ", "-"), anchor: "disqus_thread") %>

<script type="text/javascript">
    var disqus_shortname = 'ror-magick';
    var disqus_identifier = '<%= post.title %>';
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
<!--script type="text/javascript">
 
    var disqus_shortname = 'rormagick';
    var disqus_identifier = '<%= post.id %>';
    var disqus_url = '<%= url_for(:controller => "posts", :action => "view", :yy => post.created_at.strftime("%Y"), :mm => post.created_at.strftime("%m"), :id => post.title.gsub(" ", "-"), :only_path => false) %>';
 
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script--!>

app/views/posts/edit.html.haml
%h3 Edit Post

= render 'form'

app/views/posts/index.html.haml
= render 'list', posts: @posts

= link_to "new", new_admin_post_path, class: 'btn btn-primary' if current_admin_user

:javascript
  if(window.opener) {
    window.opener.location.reload(true);
    window.close()
  }

app/views/posts/new.html.haml
%h3 Add New Post

= render 'form'

app/views/posts/search.html.haml
= render 'list', posts: @posts

app/views/posts/show.html.haml
%div
  %h3= @post.title
  %p
    = format_content(@post.content)

%div
  %h3 Post a Comment
  = render 'comments', post: @post

    
= link_to "Back", :back    

app/views/posts/view.html.haml
=# render template: 'show.html.haml'
%h5= @post.created_at.strftime("%A, %d %B %Y")
.post-outer
  %h3= @post.title
  %p
    = @post.content.html_safe
  .fb-like{"data-action" => "like", "data-href" => post_show_url(yy: @post.created_at.strftime("%Y"), mm: @post.created_at.strftime("%m"), id: @post.title.gsub(" ", "-")), "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"} 
%div
  %h3 Post a Comment
  =# render 'comment_form', comment: @comment 
  
  #disqus_thread
    
= link_to "Back to the list", root_path


:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'ror-magick';
  var disqus_identifier = '<%= @post.title %>';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
  
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=430791980344979";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));