config/routes.rb
Admin::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  mount Ckeditor::Engine => "/ckeditor"

  devise_for :followers, :controllers => { :omniauth_callbacks => "followers/omniauth_callbacks" }

  resources :posts do #, except: :show
   match '(/:yy(/:mm))' => "posts#search", on: :collection, as: :search, via: :get
   resources :post_comments, path: 'comments'
  end
  get 'posts/:yy/:mm/:id' => 'posts#view', as: :post_show
  
  resources :profiles, only: :show, path: 'profile'
  resources :followers, only: :index, path: 'follower'
  
  

  root to: 'posts#index'

  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ActiveAdmin
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar
      #b-navbar
        #b-navbar-bg{style: "z-index:-1"}
        .center
          //%p.notice= notice
          //%p.alert= alert
        .align-right
          - if current_admin_user
            = current_admin_user.email
            |
            \#{link_to "Sign out", destroy_admin_user_session_path, :method => "delete"}
    #container
      #header-2
        .titlewrapper
          %h1.title
            RoR Magick
        .descriptionwrapper
          %p.description
            %span Ruby on Rails thoughts and magic's !!!
      .main-content.clearfix
        .content
          = yield
        .sidebar
          = render 'shared/sidebar'
      .footer
        = render 'shared/footer'    

:javascript
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=430791980344979";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));     

app/views/layouts/profile.html.haml
!!!
%html
  %head
    %title ActiveAdmin
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .navbar
      #b-navbar
        #b-navbar-bg{style: "z-index:-1"}
        .align-right
          - if current_admin_user
            = current_admin_user.email
            |
            \#{link_to "Sign out", destroy_admin_user_session_path, :method => "delete"}
    .container#container
      #header-2
        .titlewrapper
          %h1.title
            RoR Magick
        .descriptionwrapper
          %p.description
            %span Ruby on Rails thoughts and magic's !!!
      = yield
    .footer
      = render 'shared/footer'  